# -*- CONf -*-

# Shell configuration
shell=/bin/bash
term=foot
login-shell=no

app-id=foot
title=foot
locked-title=no

font=JetBrainsMono Nerd Font:size=11

[main]
pad=20x20

[bell]
urgent=no
notify=no
command-focused=no

[scrollback]
lines=1500
multiplier=3.0
indicator-position=relative

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode

[cursor]
style=beam
blink=yes

[mouse]
hide-when-typing=no
alternate-scroll-mode=no

[colors-dark]
# Rosé Pine Dawn
foreground=575279  # text
background=faf4ed  # base

# Normal/regular colors (color palette 0-7)
regular0=f2e9e1  # black (overlay)
regular1=b4637a  # red (love)
regular2=286983  # green (pine)
regular3=ea9d34  # yellow (gold)
regular4=56949f  # blue (foam)
regular5=907aa9  # magenta (iris)
regular6=d7827e  # cyan (rose)
regular7=575279  # white (text)

## Bright colors (color palette 8-15)
bright0=9893a5   # bright black (muted)
bright1=b4637a   # bright red
bright2=286983   # bright green
bright3=ea9d34   # bright yellow
bright4=56949f   # bright blue
bright5=907aa9   # bright magenta
bright6=d7827e   # bright cyan
bright7=575279   # bright white

[csd]

[key-bindings]
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
clipboard-copy=Control+c XF86Copy
clipboard-paste=Control+v XF86Paste
primary-paste=Shift+Insert

[search-bindings]

[url-bindings]

[mouse-bindings]



