
[general]
import = [
    "~/.config/alacritty/themes/rose_pine_dawn.toml"
]

[window]
padding = { x = 20, y = 20 }
opacity = 0.98 

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.0

[selection]
save_to_clipboard = true
